#Usamos la imagen de nodejs como base
FROM node:20

#Creamos y seleccionamos el directorio donde trabajaremos
WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn

#Exponemos el puerto donde va a correr la aplicación
EXPOSE 5000

#Iniciamos la aplicación
CMD ["yarn", "dev"]