name: sgi_frontend_prod_test
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod # Ligamos el dockerfile personalizado para producción
    ports:
      - "5001:80" # Mapea el puerto del contenedor al de tu máquina
    env_file:
      - ../.env.production