#Usamos la imagen de nodejs como base
FROM node:20

#Creamos y seleccionamos el directorio donde trabajaremos
WORKDIR /app

#Copiamos los archivos de dependencias en el directorio
COPY package.json yarn.lock ./

#Instalamos las dependencias
RUN yarn --frozen-lockfile

#Copiamos los demas archivos del proyecto
COPY . .

#Exponemos el puerto donde va a correr la aplicación
EXPOSE 5173

#Iniciamos la aplicación
CMD ["yarn", "dev"]