name: sgi-backend-prod
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod # Ligamos el dockerfile personalizado para producción
    ports:
      - "3000:3000" # Mapea el puerto del contenedor al de tu máquina
    env_file:
      - ../.env.production # Archivo con las variables de entorno