#Usamos la imagen de nodejs como base
FROM node:20

#Creamos y seleccionamos el directorio donde trabajaremos
WORKDIR /app

#Copiamos los archivos de dependencias en el directorio
#COPY package.json yarn.lock ./

#Instalamos las dependencias
RUN yarn --frozen-lockfile

#Copiamos la carpeta compilada en el directorio
COPY ./dist ./

#Exponemos el puerto donde va a correr la aplicación
EXPOSE 3000

#Compilamos el archivo

#Iniciamos la aplicación
CMD ["yarn", "start"]